name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -diff -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: TFLint
        run: tflint -f compact
